### ISSUE TITLE
Make login and register routes return a username with the token

### ISSUE THREAD

**Issue by jjcm** [jjcm/soci-backend#14]

**Comment by lapubell** [comment]
this is now complete. I did think of one outlier, social auth.

since we are only getting the email address currently, there is no way to "choose" a username. We might want to figure out how to handle this later. something like

- social login/register
- check if user has a username in the soci db
  - if so, return payload with both token and username
  - if not, return payload with token and a warning or error that the frontend can catch and show a "set your username" dialog or something
- once the username is set correctly, return the payload with both the token and the username

**Comment by jjcm** [comment]
I'm leaning towards agreeing with your initial statement that social auth isn't worth it. Let's hold off on social for now, and build as if we're gonna push forward without it.

**Comment by lapubell** [comment]
rad. I'll comment out that route so that we can't POST to it anymore, but I'll leave the code in place. We can revisit this later when it's either worth it or not.

thanks!
