### ISSUE TITLE
/comments/post/:post endpoint

### ISSUE THREAD

**Issue by jjcm** [jjcm/soci-backend#15]
_GET_ call
_Public api endpoint_

Should return all of the comments for a post. Comments should be arranged in a parent-child relationship, where only the top level comments (comments whose "parent" is null) are in the root of the array. Comments at the same level of hierarchy should be sorted by (upvotes - downvotes).

```
{
  "comments": [
    {
      "id": "YPGpbT",
      "date": "1579737064643",
      "post": "this_is_crazy", 
      "content":  "I really like this",
      "user": "bojackson",
      "upvotes": 144,
      "downvotes": 38,
      "parent": null,
      "children": [
        {
          "id": "E2j2aa",
          "date": "1579737064643",
          "post": "this_is_crazy", 
          "content": "I hate it and you suck",
          "user": "ninnymo",
          "upvotes": 22,
          "downvotes": 68,
          "parent": "YPGpbT",
          "children": null
        }
      ]
    },
    {
      "id": "qc33cG",
      "date": "1579737064643",
      "post": "this_is_crazy", 
      "content": "This reminds me of this pic",
      "user": "mamadisco",
      "upvotes": 42,
      "downvotes": 7,
      "parent": null,
      "children": null
    },

    ...etc

  ]
}
```

**Comment by lapubell** [comment]
how do you expect to reference the :post in the URL?

slug? id?

**Comment by jjcm** [comment]
Via the url. 

i.e. for this post, the url is simply `painting`
https://non.io/painting

To add a comment for that post, you'd make a post to `/comments/post/painting`

**Comment by lapubell** [comment]
I've been playing around with this a little bit and I think it makes sense to cap the recursive nature of this structure on the initial call.

currently in the docs, you have two different endpoints for these comment threads. this one gets the comments for the post, and then one more that specifically gets the details for a comment and all its children.

maybe we set up the limitations like this:
This endpoint (for the post comments) gets all top level comments and their immediate children. Then, on the frontend, if someone wants to read the whole comment thread they can click a "read more" thing or something so that you can load in that comment and all its children no matter how deep that rabbit hole goes.

Thoughts?

**Comment by jjcm** [comment]
Yea it definitely could blow up quick. `/comments/comment/[commentid]` is already a route we have spec'd out anyway, so it should be pretty easy to just call "get more comments" with that. 

I still want a bit of depth in comments on the initial load - at least something to support back and forth conversations. For now, let's limit it to 5 levels deep for the initial call. That doable?

**Comment by jjcm** [comment]
Was looking at the WIP code in this a bit, and I think the depth limit approach just by nature has an ugly exponential runtime. It's gonna be slow and ugly unless we do some serious caching with it. 

Let's change the approach: Just give me the top 100 comments sorted by score, and lets store a counter for the number of comment replies in any given comment's lineage. That way rather than showing a hefty comment depth up front, we're getting the most popular comments and we know what's missing from the comment tree. If a user clicks on "show rest of comments" I can make a request to the `/comments/comment/:comment` endpoint. 

That should be pretty easy to code up and will run much faster. Give me an offset param on it to so I can get the next 100 comments etc. Thoughts to this approach?
